language: python
python:
  - "3.5"
  - "3.6"      # current detault Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

install:
  - pip install zc.buildout==2.13.1
  - pip install virtualenv
  - buildout

script:
  - bin/pytest
